(function(){
'use strict';
const $=id=>document.getElementById(id),rows=$('contentRows'),modal=$('contentModal'),form=$('contentForm'),notice=$('contentNotice');
const typeFilter=$('contentTypeFilter'),statusFilter=$('contentStatusFilter');let posts=[],currentDetail=null;
const query=new URLSearchParams(location.search);if(['blog','newsletter'].includes(query.get('type')))typeFilter.value=query.get('type');
const user=()=>TCZKAdminAuth.storedUser()||{};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=v=>{if(!v)return'—';const d=new Date(v);return Number.isNaN(d.getTime())?String(v):d.toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'});};
const typeLabel=v=>v==='newsletter'?'Newsletter':'Blog';
const statusLabel=v=>({draft:'Draft',submitted:'Awaiting Approval',changes_requested:'Changes Requested',published:'Published',archived:'Archived',rejected:'Rejected'})[v]||v;
function show(msg,error=false){notice.hidden=false;notice.className='account-notice'+(error?' error':'');notice.textContent=msg;setTimeout(()=>notice.hidden=true,5500);}
async function load(){try{const [p,s]=await Promise.all([TCZKAdminAuth.api('/api/content/posts'),TCZKAdminAuth.api('/api/content/stats')]);posts=p.posts||[];const st=s.stats||{};$('contentBlogCount').textContent=st.blog??0;$('contentNewsletterCount').textContent=st.newsletter??0;$('contentDraftCount').textContent=(st.draft??0)+(st.changes_requested??0);$('contentPendingCount').textContent=st.submitted??0;render();}catch(e){rows.innerHTML=`<tr><td colspan="7">${esc(e.message||'Unable to load content.')}</td></tr>`;}}
function render(){const t=typeFilter.value,s=statusFilter.value;const visible=posts.filter(p=>(!t||p.type===t)&&(!s||p.status===s));if(!visible.length){rows.innerHTML='<tr><td colspan="7">No content records match this filter.</td></tr>';return;}rows.innerHTML=visible.map(p=>{const me=user(),isAdmin=me.role==='admin',canEdit=(['draft','changes_requested'].includes(p.status)&&(isAdmin||Number(p.createdBy)===Number(me.id)))||(p.status==='published'&&isAdmin);const approval=p.status==='submitted'&&isAdmin?`<a class="secondary-btn tiny" href="/admin/content/approvals/?id=${encodeURIComponent(p.id)}">Review</a>`:'';const archive=p.status==='published'&&isAdmin?`<button type="button" class="secondary-btn tiny" data-archive="${esc(p.id)}">Archive</button>`:'';const restore=p.status==='archived'&&isAdmin?`<button type="button" class="secondary-btn tiny" data-restore="${esc(p.id)}">Restore</button>`:'';const permanentDelete=p.status==='archived'&&p.type==='newsletter'&&isAdmin?`<button type="button" class="danger-btn tiny" data-delete-newsletter="${esc(p.id)}">Delete</button>`:'';const rejectedDelete=p.status==='rejected'&&isAdmin?`<button type="button" class="danger-btn tiny" data-delete-rejected="${esc(p.id)}">Delete</button>`:'';const archivedActions=p.status==='archived'&&isAdmin?`${restore}${permanentDelete}`:'';const edit=canEdit?`<button type="button" class="secondary-btn tiny" data-edit="${esc(p.id)}">Edit</button>`:'';const action=(edit||(approval||''))+(archive||'')+(archivedActions||'')+(rejectedDelete||'')||'—';return`<tr><td><strong>${esc(p.title)}</strong><br><small>/${esc(p.slug)}</small>${p.featured?'<br><small>★ Featured</small>':''}${p.currentNewsletter?'<br><small>◆ Current newsletter</small>':''}</td><td><span class="role-badge ${p.type==='newsletter'?'admin':'editor'}">${typeLabel(p.type)}</span></td><td><span class="workflow-status ${esc(p.status)}">${statusLabel(p.status)}</span></td><td>${fmt(p.publicationDate)}</td><td>${esc(p.createdByName||p.createdByEmail||'—')}</td><td>${fmt(p.updatedAt)}</td><td><div class="table-actions">${action}</div></td></tr>`;}).join('');rows.querySelectorAll('[data-edit]').forEach(b=>b.addEventListener('click',()=>openEdit(b.dataset.edit)));rows.querySelectorAll('[data-archive]').forEach(b=>b.addEventListener('click',()=>archivePost(b.dataset.archive)));rows.querySelectorAll('[data-restore]').forEach(b=>b.addEventListener('click',()=>restorePost(b.dataset.restore)));rows.querySelectorAll('[data-delete-newsletter]').forEach(b=>b.addEventListener('click',()=>deleteArchivedNewsletter(b.dataset.deleteNewsletter)));rows.querySelectorAll('[data-delete-rejected]').forEach(b=>b.addEventListener('click',()=>deleteRejectedPublication(b.dataset.deleteRejected)));}
async function archivePost(id){const p=posts.find(x=>x.id===id);if(!p)return;if(!confirm(`Archive “${p.title}”? It will disappear from the public Blog/Newsletter endpoints, but its D1 record, audit history, and R2 files will be preserved.`))return;try{await TCZKAdminAuth.api('/api/content/posts/archive',{method:'POST',body:JSON.stringify({id})});show('Publication archived. It is no longer public.');await load();}catch(e){show(e.message||'Unable to archive publication.',true);}}
async function restorePost(id){const p=posts.find(x=>x.id===id);if(!p)return;if(!confirm(`Restore “${p.title}” to Published? It will become public again. Featured newsletter status is not restored automatically.`))return;try{await TCZKAdminAuth.api('/api/content/posts/restore',{method:'POST',body:JSON.stringify({id})});show('Publication restored to Published.');await load();}catch(e){show(e.message||'Unable to restore publication.',true);}}
async function deleteArchivedNewsletter(id){const p=posts.find(x=>x.id===id);if(!p||p.type!=='newsletter'||p.status!=='archived')return;const typed=prompt(`Permanently delete archived newsletter “${p.title}”?\n\nThis removes its D1 record and associated PDF/cover files from zk-publications. Audit history remains.\n\nType the newsletter slug exactly to confirm:\n${p.slug}`);if(typed===null)return;if(typed.trim()!==p.slug){show('Delete cancelled: slug did not match.',true);return;}if(!confirm('This action cannot be undone. Permanently delete this archived newsletter now?'))return;try{const res=await TCZKAdminAuth.api('/api/content/posts/delete-archived-newsletter',{method:'POST',body:JSON.stringify({id,confirmSlug:p.slug})});show(res.r2DeleteWarnings?.length?'Newsletter deleted from D1. Some R2 cleanup reported warnings; see Worker logs.':'Archived newsletter permanently deleted.');await load();}catch(e){show(e.message||'Unable to permanently delete newsletter.',true);}}
async function deleteRejectedPublication(id){const p=posts.find(x=>x.id===id);if(!p||p.status!=='rejected')return;const typed=prompt(`Permanently delete rejected ${p.type==='newsletter'?'newsletter':'blog post'} “${p.title}”?\n\nThis removes the rejected D1 record and its uploaded PDF/cover files from zk-publications. Audit history remains.\n\nType the publication slug exactly to confirm:\n${p.slug}`);if(typed===null)return;if(typed.trim()!==p.slug){show('Delete cancelled: slug did not match.',true);return;}if(!confirm('This action cannot be undone. Permanently delete this rejected publication now?'))return;try{await TCZKAdminAuth.api('/api/content/posts/delete-rejected',{method:'POST',body:JSON.stringify({id,confirmSlug:p.slug})});show('Rejected publication permanently deleted.');await load();}catch(e){show(e.message||'Unable to permanently delete rejected publication.',true);}}
function toggleNewsletter(){const is=$('contentType').value==='newsletter';document.querySelectorAll('.newsletter-only').forEach(el=>el.hidden=!is);if(!is)$('contentCurrentNewsletter').checked=false;}
function setAssetLabels(assets=[]){const staged={pdf:null,cover:null},published={pdf:null,cover:null};for(const a of assets){if(a.status==='staged'&&!staged[a.kind])staged[a.kind]=a;if(a.status==='published'&&!published[a.kind])published[a.kind]=a;}for(const kind of ['pdf','cover']){const a=staged[kind]||published[kind],el=$(kind+'AssetStatus');el.textContent=a?`${a.status==='staged'?'Ready to submit':'Published'} · ${a.originalName} · ${Math.max(1,Math.round(a.sizeBytes/1024))} KB`:`No ${kind==='pdf'?'PDF':'cover'} attached.`;el.dataset.hasAsset=a?'1':'0';}}
async function openEdit(id){currentDetail=null;let p=null,assets=[];if(id){try{const res=await TCZKAdminAuth.api('/api/content/post?id='+encodeURIComponent(id));p=res.post;assets=res.assets||[];currentDetail=res;}catch(e){show(e.message,true);return;}}$('contentModalTitle').textContent=p?'Edit Publication':'New Publication';$('contentId').value=p?.id||'';$('contentType').value=p?.type||query.get('type')||'blog';$('contentPublicationDate').value=p?.publicationDate||'';$('contentTitle').value=p?.title||'';$('contentSlug').value=p?.slug||'';$('contentSummary').value=p?.summary||'';$('contentAuthor').value=p?.authorName||'';$('contentCategories').value=(p?.categories||[]).join(', ');$('contentSeason').value=p?.season||'';$('contentYear').value=p?.year||'';$('contentAuthorImageUrl').value=p?.authorImageUrl||'';$('contentFeatured').checked=Boolean(p?.featured);$('contentCurrentNewsletter').checked=Boolean(p?.currentNewsletter);$('contentPdf').value='';$('contentCover').value='';setAssetLabels(assets);const systemInfo=$('contentSystemInfo');if(p?.id){systemInfo.hidden=false;$('contentSystemId').textContent=p.id;$('contentSystemStatus').textContent=statusLabel(p.status);}else{systemInfo.hidden=true;$('contentSystemId').textContent='—';$('contentSystemStatus').textContent='—';}toggleNewsletter();const note=p?.reviewNote||'';$('contentReviewNote').hidden=!note;$('contentReviewNote').textContent=note?`Admin review note: ${note}`:'';const isPublished=p?.status==='published';$('submitContentPost').disabled=isPublished;$('submitContentPost').hidden=isPublished;$('contentPdf').disabled=isPublished;$('contentCover').disabled=isPublished;$('saveContentDraft').textContent=isPublished?'Save Published Changes':'Save Draft';$('assetHint').textContent=isPublished?'Published metadata can be edited here. PDF and cover replacement remains version-controlled and is not changed by this form.':'For a new post, files upload automatically after the draft record is created.';$('contentWorkflowNote').textContent=isPublished?'Changes to published metadata go live immediately after saving.':(p?.status==='changes_requested'?'Update the returned draft and files, then resubmit for approval.':'Save metadata, attach a PDF and cover, then submit for approval.');modal.hidden=false;document.body.classList.add('modal-open');}
function close(){modal.hidden=true;document.body.classList.remove('modal-open');}
function payload(){return{id:$('contentId').value,type:$('contentType').value,publicationDate:$('contentPublicationDate').value,title:$('contentTitle').value,slug:$('contentSlug').value,summary:$('contentSummary').value,authorName:$('contentAuthor').value,categories:$('contentCategories').value.split(',').map(x=>x.trim()).filter(Boolean),season:$('contentSeason').value,year:$('contentYear').value,authorImageUrl:$('contentAuthorImageUrl').value,featured:$('contentFeatured').checked,currentNewsletter:$('contentType').value==='newsletter'&&$('contentCurrentNewsletter').checked};}
async function uploadAsset(postId,kind,file){if(!file)return null;const base=String(window.TCZK_ADMIN_API||'').replace(/\/$/,'');const path=`/api/content/assets/upload?postId=${encodeURIComponent(postId)}&kind=${encodeURIComponent(kind)}&filename=${encodeURIComponent(file.name)}`;const res=await fetch(base+path,{method:'POST',headers:{Authorization:'Bearer '+TCZKAdminAuth.token(),'Content-Type':file.type||'application/octet-stream'},body:file});const data=await res.json().catch(()=>({}));if(!res.ok||data.ok===false)throw new Error(data.error||`Unable to upload ${kind}.`);return data.asset;}
async function saveDraft(){const id=$('contentId').value,body=payload();const res=await TCZKAdminAuth.api(id?'/api/content/posts/update':'/api/content/posts/create',{method:'POST',body:JSON.stringify(body)});const post=res.post;await uploadAsset(post.id,'pdf',$('contentPdf').files[0]);await uploadAsset(post.id,'cover',$('contentCover').files[0]);return post.id;}
form.addEventListener('submit',async e=>{e.preventDefault();const btn=$('saveContentDraft');btn.disabled=true;btn.textContent='Saving…';try{const id=await saveDraft();show(currentDetail?.post?.status==='published'?'Published metadata updated.':'Draft and attached files saved.');await load();await openEdit(id);}catch(err){show(err.message||'Unable to save draft.',true);}finally{btn.disabled=false;btn.textContent=currentDetail?.post?.status==='published'?'Save Published Changes':'Save Draft';}});
$('submitContentPost').addEventListener('click',async()=>{const btn=$('submitContentPost');btn.disabled=true;btn.textContent='Saving & Submitting…';try{const id=await saveDraft();await TCZKAdminAuth.api('/api/content/posts/submit',{method:'POST',body:JSON.stringify({id})});close();show('Publication submitted for Admin approval.');await load();}catch(e){show(e.message||'Unable to submit publication.',true);}finally{btn.disabled=false;btn.textContent='Submit for Approval';}});
$('newContentPost').addEventListener('click',()=>openEdit(null));$('cancelContentEdit').addEventListener('click',close);modal.addEventListener('click',e=>{if(e.target===modal)close();});typeFilter.addEventListener('change',render);statusFilter.addEventListener('change',render);$('contentType').addEventListener('change',toggleNewsletter);$('contentPdf').addEventListener('change',()=>{$('pdfAssetStatus').textContent=$('contentPdf').files[0]?`Selected: ${$('contentPdf').files[0].name}`:$('pdfAssetStatus').textContent;});$('contentCover').addEventListener('change',()=>{$('coverAssetStatus').textContent=$('contentCover').files[0]?`Selected: ${$('contentCover').files[0].name}`:$('coverAssetStatus').textContent;});
if(query.get('new')==='1')setTimeout(()=>openEdit(null),0);load();
})();
